### ISSUE TITLE
Extra space in delimiter in CSVs causes some difficulties with Python Pandas integration.

### ISSUE THREAD

**Issue by IanTBlack** [OceanOptics/Inlinino#4]
I was having some difficulties reading in the CSVs with Pandas during the Inline Workshop.  There is an extra space between header columns and variables in output CSVs. In Pandas (1.4.3), `pandas.read_csv` initially assumes a comma separator. The extra space prevents Pandas from determining the datatype, so all data is then read in as strings, making it difficult to perform operations.

A workaround for this in Pandas is to specify the delimiter to include a space after the comma. If this extra space causes problems elsewhere, a possible fix in Inlinino might be to change how the delimiter is written in log.py.

For Pandas, instead of using default settings with something like this.

```
pandas.read_csv('filename_here', header = [0,1])
```

Specifying the separator/delimiter will allow Pandas to infer the datatype.

```
pandas.read_csv('filename_here', header=[0,1], sep = ", " # There is a space after the comma.
```

Specifying the delimiter this way may throw a warning stating that Pandas will fall back to using the Python engine for regex support. Presumably the only downside to this is an increased time to import data if the file is large.

**Comment by doizuc** [comment]
Thank you Ian. I tested reading data with [InLineAnalysis](https://github.com/OceanOptics/InLineAnalysis) and removing the space doesn't affect importation. As suggested, I removed the extra space in the log.py to conform with standard csv format (RFC 4180). Commit: a4cf3c395f9b727bd34f25e16e310377cfc631ea
